config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root "contacts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true, numericality: true, inclusion: { in: 20...100, message: "must be between 20 and 100" }
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :find_all_contacts
  before_action :find_contact, except: [:new, :create, :index]

  def index
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      flash[:notice] = "Contact created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @contact.update(contact_params)
      flash[:notice] = "Contact updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @contact.destroy
    flash[:notice] = "Contact removed"
    render turbo_stream: [
      turbo_stream.update("flash", partial: "shared/flash"),
      turbo_stream.remove(dom_id(@contact)),
      turbo_stream.update("contacts-count", partial: "contacts/count", locals: { contacts: @contacts })
    ]
  end

  private

    def contact_params
      params.require(:contact).permit!
    end

    def find_all_contacts
      @contacts = Contact.all
    end

    def find_contact
      @contact = Contact.find(params.require(:id))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def inline_error_for(field, form_obj)
    html = []

    if form_obj.errors[field].any?
      html << form_obj.errors[field].map do |msg|
        tag.div(msg, class: "text-red-400 text-xs m-0 p-0 text-right mb-2")
      end
    end

    html.join.html_safe
  end
end

app/views/contacts/_contact.html.erb
<tr id="<%= dom_id(contact) %>" data-stream-enter-class="animate-item-in" data-stream-exit-class="animate-item-out">
  <td><%= contact.id %></td>
  <td><%= link_to contact.name, contact_path(contact), data: { turbo_frame: "_top" } %></td>
  <td><%= contact.age %></td>
  <td><%= contact.email %></td>
  <td><%= link_to "Edit", edit_contact_path(contact), class: "btn btn-link btn-sm", data: { turbo_frame: "_top" } %></td>
  <td><%= button_to "Delete", contact_path(contact), method: :delete, class: "btn btn-link btn-sm" %></td>
</tr>

app/views/contacts/_count.html.erb
<span data-stream-enter-class="animate-item-in" data-stream-exit-class="animate-item-out">Showing <%= contacts.length %> <%= "contact".pluralize(contacts.length) %></span>

app/views/contacts/_form.html.erb
<%= form_for contact do |f| %>
  <% if contact.errors.any? %>
    <div class="form-errors">
      <div class="alert shadow-lg alert-error text-white">
        Your form's got some errors
      </div>
    </div>
  <% end %>
  <%= f.text_field :name, placeholder: "Your first name", class: "input input-bordered w-full max-w-xs my-5" %>
  <%= inline_error_for(:name, contact) %>
  <%= f.text_field :age, placeholder: "Your age", class: "input input-bordered w-full max-w-xs my-4" %>
  <%= inline_error_for(:age, contact) %>
  <%= f.text_field :email, placeholder: "Your email address", class: "input input-bordered w-full max-w-xs my-4" %>
  <%= inline_error_for(:email, contact) %>
  <%= f.submit "Save", class: "form-control btn btn-primary my-4" %>
<% end %>

app/views/contacts/_list.html.erb
<table class="table table-zebra mt-0 w-full">
  <thead>
    <tr class="w-full">
      <th class="text-left">ID</th>
      <th class="text-left">Name</th>
      <th class="text-left">Age</th>
      <th class="text-left">Email</th>
      <th class="text-center" colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody id="contacts-list" data-controller="contacts" data-action="">
  <% contacts.each do |contact| %>
    <%= render partial: "contact", locals: { contact: contact }  %>
  <% end %>
  </tbody>
</table>
<div class="text-gray-400 mt-4 text-xs text-right" id="contacts-count">
  <%= render partial: "count", locals: { contacts: contacts } %>
</div>

app/views/contacts/create.turbo_stream.erb
<%= turbo_stream.update("flash", partial: "shared/flash") %>
<%= turbo_stream.append("contacts-list", partial: "contacts/contact", locals: { contact: @contact }) %>
<%= turbo_stream.update("contacts-count", partial: "contacts/count", locals: { contacts: @contacts }) %>
<%= turbo_stream.update("contact-form", partial: "contacts/form", locals: { contact: Contact.new }) %>

app/views/contacts/edit.html.erb
<div class="prose lg:prose-xl">
  <h1>Edit contact</h1>
</div>

<div class="grid grid-cols-2 gap-4 mt-8">
  <div class="bg-gray-100 p-8">
    <%= render partial: "list", locals: { contacts: @contacts } %>
  </div>
  <div class="form-control w-full max-w-xs">
    <%= render partial: "form", locals: { contact: @contact } %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="prose lg:prose-xl">
  <h1>Contacts list</h1>

  <%= link_to "Add new contact", new_contact_path, class: "btn btn-primary" %>
</div>

app/views/contacts/new.html.erb
<div class="prose lg:prose-xl">
  <h1>New contact</h1>
</div>

<div class="grid grid-cols-2 gap-4 mt-8">
  <div class="bg-gray-100 p-8">
    <%= render partial: "list", locals: { contacts: @contacts } %>
  </div>
  <div class="form-control w-full max-w-xs" id="contact-form">
    <%= render partial: "form", locals: { contact: @contact } %>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="prose lg:prose-xl">
  <h1>Contact details</h2>
</div>

<div class="w-1/2 mx-auto p-8 border-2 m-8 grid grid-cols-2 gap-4">
  <div>
  <div class="my-4">Name: <%= @contact.name %></div>
  <hr />
  <div class="my-4">Age: <%= @contact.age %></div>
  <hr />
  <div class="my-4">Email: <%= @contact.email %></div>
  </div>
  <div>
    <img src="https://i.pravatar.cc/300" />
  </div>
</div>

app/views/contacts/update.turbo_stream.erb
<%= turbo_stream.update("flash", partial: "shared/flash") %>
<%= turbo_stream.replace(dom_id(@contact), partial: "contacts/contact", locals: { contact: @contact }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="emerald">
  <head>
    <title>HotwireForms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container mx-auto">
      <div class="py-8">
        <div id="flash" class="flash">
          <%= render partial: "shared/flash" %>
        </div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <% alert_class = type == "notice" ? "success" : "error" %>
  <div class="alert alert-<%= alert_class %> mb-8 text-white" data-stream-enter-class="animate-in" data-stream-exit-class="animate-out">
    <%= msg %>
  </div>
<% end %>